Watchlist/config/routes.rb
Rails.application.routes.draw do
  resources :series
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'series#index'
end

Watchlist/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Watchlist/app/models/series.rb
class Series < ApplicationRecord
  validates :season, presence: true, numericality: { greater_than_or_equal_to: 1 }
  validates :episode, presence: true, numericality: { greater_than_or_equal_to: 1 }
end

Watchlist/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Watchlist/app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: [:show, :edit, :update, :destroy]

  # GET /series
  # GET /series.json
  def index
    @series = Series.all
  end

  # GET /series/1
  # GET /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = Series.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series
  # POST /series.json
  def create
    @series = Series.new(series_params)

    respond_to do |format|
      if @series.save
        format.js
        format.html { redirect_to @series, notice: 'Series was successfully created.' }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1
  # PATCH/PUT /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to @series, notice: 'Series was successfully updated.' }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to series_index_url, notice: 'Series was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.require(:series).permit(:name, :season, :episode)
    end
end

Watchlist/app/helpers/application_helper.rb
module ApplicationHelper
end

Watchlist/app/helpers/series_helper.rb
module SeriesHelper
end

Watchlist/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Watchlist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Watchlist/app/views/series/_form.html.erb
<%= form_with(model: series) do |form| %>
  <% if series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
        <% series.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :season %>
    <%= form.number_field :season %>
  </div>

  <div class="field">
    <%= form.label :episode %>
    <%= form.number_field :episode %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Watchlist/app/views/series/_series.html.erb
  <tr>
    <td><%= series.name %></td>
    <td><%= series.season %></td>
    <td><%= series.episode %></td>
    <td><%= link_to 'Show', series %></td>
    <td><%= link_to 'Edit', edit_series_path(series) %></td>
    <td><%= link_to 'Destroy', series, method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: "delete"  %></td>
  </tr>

Watchlist/app/views/series/create.js.erb
$('#new-series form').remove();
$('#new-series a').show();
$('table#series_table tbody').append(" <%= j render @series %>");

Watchlist/app/views/series/destroy.js.erb
$('.delete').bind('ajax:success', function () {
    console.log('yo i am deleting');
    $(this).closest('tr').fadeOut();
});

Watchlist/app/views/series/edit.html.erb
<h1>Editing Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Show', @series %> |
<%= link_to 'Back', series_index_path %>

Watchlist/app/views/series/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Series</h1>

<table id="series_table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Season</th>
      <th>Episode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   <%= render @series %>
  </tbody>
</table>

<br>
<div id="new-series">
  <%= link_to 'New Series', new_series_path , remote: true %>
</div>

Watchlist/app/views/series/new.html.erb
<h1>New Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Back', series_index_path %>

Watchlist/app/views/series/new.js.erb
$('#new-series a').hide().parent().append( "<%= j render 'form', series: @series %> ");

Watchlist/app/views/series/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @series.name %>
</p>

<p>
  <strong>Season:</strong>
  <%= @series.season %>
</p>

<p>
  <strong>Episode:</strong>
  <%= @series.episode %>
</p>

<%= link_to 'Edit', edit_series_path(@series) %> |
<%= link_to 'Back', series_index_path %>